baseURL = 'https://netisack.nekoweb.org'
languageCode = 'en-us'
title = 'NETiSACK'
theme = 'mainroad'

[Params.logo]
  image = false
  title = "NETiSACK"
  subtitle = "the little corner of the internet, but we do silicon drugs here."

[Params]
  post_meta = ["author", "date", "categories"]

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["about", "skills", "recent", "categories", "taglist"]

[Params.widgets.social]
  github = "NETiSACK"